
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."reminderType" AS ENUM (
    'DAYS',
    'HOURS'
);

ALTER TYPE "public"."reminderType" OWNER TO "postgres";

CREATE TYPE "public"."sex" AS ENUM (
    'MALE',
    'FEMALE'
);

ALTER TYPE "public"."sex" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."appointment" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "specialtyId" "uuid",
    "userId" "uuid" DEFAULT "gen_random_uuid"(),
    "address" "json",
    "reminderValue" integer,
    "reminderType" "public"."reminderType"
);

ALTER TABLE "public"."appointment" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."examType" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."examType" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."exams" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userId" "uuid",
    "examTypeId" "uuid"
);

ALTER TABLE "public"."exams" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."glucose" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" integer,
    "userId" "uuid" DEFAULT "gen_random_uuid"()
);

ALTER TABLE "public"."glucose" OWNER TO "postgres";

ALTER TABLE "public"."glucose" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."glucose_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."medicine" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "isContinuous" boolean NOT NULL,
    "finalDate" timestamp with time zone NOT NULL,
    "isFinished" boolean NOT NULL,
    "intervalInMinutes" bigint,
    "userId" "uuid"
);

ALTER TABLE "public"."medicine" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."pressure" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "numerator" integer,
    "denominator" integer,
    "userId" "uuid" DEFAULT "gen_random_uuid"()
);

ALTER TABLE "public"."pressure" OWNER TO "postgres";

ALTER TABLE "public"."pressure" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pressure_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."specialty" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text"
);

ALTER TABLE "public"."specialty" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_info" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "height" integer,
    "birth_date" "date" NOT NULL,
    "sex" "public"."sex"
);

ALTER TABLE "public"."user_info" OWNER TO "postgres";

COMMENT ON TABLE "public"."user_info" IS 'tabela referente aos usuários do app';

CREATE TABLE IF NOT EXISTS "public"."weight" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" real,
    "userId" "uuid" DEFAULT "gen_random_uuid"()
);

ALTER TABLE "public"."weight" OWNER TO "postgres";

ALTER TABLE "public"."weight" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."weight_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."appointment"
    ADD CONSTRAINT "appointment_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."examType"
    ADD CONSTRAINT "examType_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."examType"
    ADD CONSTRAINT "examType_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."exams"
    ADD CONSTRAINT "exams_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."glucose"
    ADD CONSTRAINT "glucose_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."medicine"
    ADD CONSTRAINT "medicine_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."pressure"
    ADD CONSTRAINT "pressure_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."specialty"
    ADD CONSTRAINT "specialty_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_info"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."weight"
    ADD CONSTRAINT "weight_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."appointment"
    ADD CONSTRAINT "public_appointment_specialtyId_fkey" FOREIGN KEY ("specialtyId") REFERENCES "public"."specialty"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."appointment"
    ADD CONSTRAINT "public_appointment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user_info"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."exams"
    ADD CONSTRAINT "public_exams_examTypeId_fkey" FOREIGN KEY ("examTypeId") REFERENCES "public"."examType"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."exams"
    ADD CONSTRAINT "public_exams_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user_info"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."glucose"
    ADD CONSTRAINT "public_glucose_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user_info"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."medicine"
    ADD CONSTRAINT "public_medicine_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user_info"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."pressure"
    ADD CONSTRAINT "public_pressure_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user_info"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_info"
    ADD CONSTRAINT "public_user_info_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."weight"
    ADD CONSTRAINT "public_weight_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user_info"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."appointment" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."examType" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."exams" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."glucose" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."medicine" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."pressure" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."specialty" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_info" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."weight" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."appointment" TO "anon";
GRANT ALL ON TABLE "public"."appointment" TO "authenticated";
GRANT ALL ON TABLE "public"."appointment" TO "service_role";

GRANT ALL ON TABLE "public"."examType" TO "anon";
GRANT ALL ON TABLE "public"."examType" TO "authenticated";
GRANT ALL ON TABLE "public"."examType" TO "service_role";

GRANT ALL ON TABLE "public"."exams" TO "anon";
GRANT ALL ON TABLE "public"."exams" TO "authenticated";
GRANT ALL ON TABLE "public"."exams" TO "service_role";

GRANT ALL ON TABLE "public"."glucose" TO "anon";
GRANT ALL ON TABLE "public"."glucose" TO "authenticated";
GRANT ALL ON TABLE "public"."glucose" TO "service_role";

GRANT ALL ON SEQUENCE "public"."glucose_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."glucose_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."glucose_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."medicine" TO "anon";
GRANT ALL ON TABLE "public"."medicine" TO "authenticated";
GRANT ALL ON TABLE "public"."medicine" TO "service_role";

GRANT ALL ON TABLE "public"."pressure" TO "anon";
GRANT ALL ON TABLE "public"."pressure" TO "authenticated";
GRANT ALL ON TABLE "public"."pressure" TO "service_role";

GRANT ALL ON SEQUENCE "public"."pressure_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pressure_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pressure_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."specialty" TO "anon";
GRANT ALL ON TABLE "public"."specialty" TO "authenticated";
GRANT ALL ON TABLE "public"."specialty" TO "service_role";

GRANT ALL ON TABLE "public"."user_info" TO "anon";
GRANT ALL ON TABLE "public"."user_info" TO "authenticated";
GRANT ALL ON TABLE "public"."user_info" TO "service_role";

GRANT ALL ON TABLE "public"."weight" TO "anon";
GRANT ALL ON TABLE "public"."weight" TO "authenticated";
GRANT ALL ON TABLE "public"."weight" TO "service_role";

GRANT ALL ON SEQUENCE "public"."weight_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."weight_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."weight_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
